### ISSUE TITLE
Problem running the script on RP3

### ISSUE THREAD

**Issue by AmitMY** [Zacho2/PiCloud#1]
I don't have much experience with Linux, so I'd really love to have this script working on my device.

I ran this command:
`sudo ./picloud.sh -s "10.0.0.9 admin password"`

And got this:
> Running setup...
> mkdir: cannot create directory ‘/mnt/MyCloud’: File exists
> mount error(115): Operation now in progress
> Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
> rmdir: failed to remove ‘/mnt/MyCloud’: Device or resource busy
> Mounting MyCloud failed during setup

I doubt I am doing something wrong, as this is pretty straight forward. What should I check/what data can I give so a solution could be found?

**Comment by AmitMY** [comment]
Investigated a bit:
`/mnt/MyCloud` is my device mounted successfully.
When I do:
```
cd /mnt/MyCloud
mkdir test
```
It works, and I can see that dir from a different computer.

However, when trying to execute:
`sudo ./picloud.sh`

I get this output:
> Creating backup. This may take a while.
> Unable to find suitable address.
> mount error(115): Operation now in progress
> Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
> Mounting MyCloud failed

I find it odd, as I have checked, and MyCloud is mounted just fine

**Comment by AmitMY** [comment]
I think this is the solution:
The source code has:
`dd if=/dev/mmcblk0p7 bs=1M | gzip > /mnt/MyCloud/images/"$(date +%d-%b-%y_%T)".gz`

The code should run: `lsblk` to get the hard drive, because in my case I have:

> mmcblk0
> |--mmcblk0p1
> |--mmcblk0p2

So when I ran this command:
`sudo dd if=/dev/mmcblk0 bs=1M | gzip > /mnt/MyCloud/"$(date +%FT%T)".gz`
(I changed the drive, and the date format for a sortable format)

It works.

**Comment by Zacho2** [comment]
Glad you got it working 👍 

It looks like different SD cards may have different partition aliases (eg `mmcblk0p1`) where the operating system resides. Perhaps the script needs some integrated logic to figure out which partition contains the OS. If you have any ideas or want to submit a pull request you're more than welcome. I also like the improvements you made to the date formatting.

**Comment by AmitMY** [comment]
Is there a reason to backup just the OS partition? Why not backup the entire thing?

**Comment by AmitMY** [comment]
I added 5 PRs. merge whichever you want.

**Comment by Zacho2** [comment]
Thanks! I tested backing up the whole file system instead of a particular partition and it had no issues. So I agree that it may as well back up the entire thing.

I'll take a look at the PRs shortly.
