### ISSUE TITLE
Device is not actually mounted

### ISSUE THREAD

**Issue by AmitMY** [Zacho2/PiCloud#10]
- I probably made a mistake. After you add the mountpoint at line 44, you do need to run `mount -a`. So the check should be `! (mount -a && mountpoint -q /mnt/MyCloud)`
- Here is a [superuser question](http://superuser.com/questions/1166991/check-if-something-is-mounted/1166995?noredirect=1#comment1683754_1166995) I opened because I didn't understand why my mount check failed for me: 

Sorry for my mistake.

However, I am opening an issue because the mounting (`mount -a`) says that the device is busy, and if I try to `rmdir /mnt/MyCloud` it fails as the device is busy. I checked who has it locked, and it seems like a kernel process has it locked. Did you encounter such problem? (yes, this happens even after a reboot, so I'm in a twilight zone - halfway mounter :))

**Comment by Zacho2** [comment]
You are correct, the mount command is needed. No problem. We can fix that easily.

Have you tried unmounting the device using the `umount` command?

**Comment by AmitMY** [comment]
Running `umount` is no help, as the drive was not officialy mounted, but in some kind of "limbo" zone.
I just tried again `sudo rmdir` and it worked. then I modified the file and added `mount -a` 1 line above the `if ! (mountpoint -q /mnt/MyCloud); then`, in setup, and ran setup again. It is now a mountpoint.

Thanks for all the help and for writing this script!
