### ISSUE TITLE
Bad merge reverting changes

### ISSUE THREAD

**Issue by AmitMY** [Zacho2/PiCloud#7]
I created 5 PRs, so you could merge each individually, and only what you agree with.
unfortunately, because all of those PRs are for the same lines of code, it got messed up, as you can see from this commit:  (changing BS, but reverting date)
![image](https://cloud.githubusercontent.com/assets/5757359/21922982/33f849b2-d97a-11e6-8297-f10fcd5811dd.png)

This is the output of the correct merge:
```
# Create a compressed backup of SD card image
echo "Creating backup. This may take a while."
if mountpoint -q /mnt/MyCloud; then
	sync # Syncs files in cache
	dd if=/dev/mmcblk0 bs=64k | gzip > /mnt/MyCloud/images/"$(date +%FT%T)".gz
	echo "Backup complete at $(date +%FT%T)"
else
	echo "MyCloud is not mounted. Please go through setup"
	exit 1
fi
```

**Comment by Zacho2** [comment]
Fixed by 957dcf6
